apiVersion: apps/v1
kind: Deployment
metadata:
  name: webhook-notification-server-deployment
spec:
  selector:
    matchLabels:
        app: webhook-notification-server
  replicas: 1
  template:
    metadata:
        labels: 
            app: webhook-notification-server
    spec:
        containers: 
            - name: webhook-notification-server
              image: <UPDATE VALUE>
              ports:
                - containerPort: 5080
---
apiVersion: v1
kind: Service
metadata:
    name: webhook-notification-server-service
    labels: 
        app: webhook-notification-server
spec:
    selector:
        app: webhook-notification-server
    ports:
    - protocol: TCP
        port: 5080
        targetPort: 5080